name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
      
jobs:
  dnsdist:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [ "16" ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro powerdns/dnsdist-${{ matrix.version}}

    - name: Run Python tests
      run: |
        sudo python3 -m pip install -r requirements.txt 
        sudo python3 -m pip install --upgrade dnspython
        sudo python3 -m unittest tests.test_console
        sudo python3 -m unittest tests.test_key
        sudo python3 -m unittest tests.test_statistics