name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  dnsdist-e2e:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        dnsdist: [ "dnsdist-16", "dnsdist-17" ]
        python: [ "3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python}}

    - name: Install Python requirements
      run: |
        sudo python3 -m pip install -r requirements.txt 
        sudo python3 -m pip install --upgrade dnspython

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro powerdns/${{ matrix.dnsdist}}
        sudo docker logs dnsdist
        dig -p 5553 www.github.com @127.0.0.1 +timeout=10 +tries=3 +retry=3 | grep NOERROR
        
    - name: Run Python tests
      run: |
        sudo python3 -m unittest tests.test_console
        sudo python3 -m unittest tests.test_key
        sudo python3 -m unittest tests.test_statistics
        sudo python3 -m unittest tests.test_hashpwd
